services:
  db:
    image: mariadb:latest
    container_name: columnistos-mariadb
    environment:
      MYSQL_DATABASE: columnistos
      MYSQL_USER: ${DB_USER}
      MARIADB_ROOT_PASSWORD: ${DB_PWD}
    ports:
      - "3306:3306"
