service: columnistosjs

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

package:
  excludeDevDependencies: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  post:
    handler: post.handler
    timeout: 30
    events:
      - schedule: cron(57 17 * * ? *)
    environment:
      WAFRN_EMAIL: ${env:WAFRN_EMAIL}
      WAFRN_PASSWORD: ${env:WAFRN_PASSWORD}
    vpc:
      securityGroupIds:
        - ${env:AWS_LAMBDA_SG}
      subnetIds:
        - ${env:AWS_SUBNET_ID_1}
        - ${env:AWS_SUBNET_ID_2}

custom:
  webpack:
    webpackConfig: ./webpack.config.cjs
