service: columnistosjs

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  vpc:
    securityGroupIds:
      - ${env:AWS_LAMBDA_SG}
      - ${env:AWS_RDS_SG}
    subnetIds:
      - ${env:AWS_SUBNET_ID_1}
      - ${env:AWS_SUBNET_ID_2}
      - ${env:AWS_SUBNET_ID_3}
      - ${env:AWS_SUBNET_ID_4}

package:
  excludeDevDependencies: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  post:
    handler: scripts/post.handler
    timeout: 30
    events:
      - schedule: cron(01 20 * * ? *)
    environment:
      WAFRN_EMAIL: ${env:WAFRN_EMAIL}
      WAFRN_PASSWORD: ${env:WAFRN_PASSWORD}
      DB_HOST: ${env:DB_HOST}
      DB_USER: ${env:DB_USER}
      DB_PWD: ${env:DB_PWD}
  crawl:
    handler: scripts/crawl.handler
    timeout: 30
    events:
      - schedule: cron(45 * * * ? *)
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_USER: ${env:DB_USER}
      DB_PWD: ${env:DB_PWD}

custom:
  webpack:
    webpackConfig: ./webpack.config.cjs
