apiVersion: v1
kind: Namespace
metadata:
  name: columnistos
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawl
  namespace: columnistos
spec:
  schedule: "55 13-23,00-05 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400 # Retener pod por 1 día
      template:
        spec:
          imagePullSecrets:
            - name: ghcr-secret
          containers:
            - name: crawl
              image: ghcr.io/__GH_OWNER__/columnistosjs/crawl:__VERSION__
              imagePullPolicy: IfNotPresent
              env:
                - name: WAFRN_EMAIL
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: WAFRN_EMAIL
                - name: WAFRN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: columnistos-secret
                      key: WAFRN_PASSWORD
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: DB_HOST
                - name: DB_USER
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: DB_USER
                - name: DB_PWD
                  valueFrom:
                    secretKeyRef:
                      name: columnistos-secret
                      key: DB_PWD
                - name: CRAWLER_DIR
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: CRAWLER_DIR
                - name: ADMIN_HANDLES
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: ADMIN_HANDLES
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: post
  namespace: columnistos
spec:
  schedule: "00 16-23 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400 # Retener pod por 1 día
      template:
        spec:
          imagePullSecrets:
            - name: ghcr-secret
          containers:
            - name: post
              image: ghcr.io/__GH_OWNER__/columnistosjs/post:__VERSION__
              imagePullPolicy: IfNotPresent
              env:
                - name: WAFRN_EMAIL
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: WAFRN_EMAIL
                - name: WAFRN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: columnistos-secret
                      key: WAFRN_PASSWORD
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: DB_HOST
                - name: DB_USER
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: DB_USER
                - name: DB_PWD
                  valueFrom:
                    secretKeyRef:
                      name: columnistos-secret
                      key: DB_PWD
                - name: ADMIN_HANDLES
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: ADMIN_HANDLES
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: send-dms
  namespace: columnistos
spec:
  schedule: "20,30,40 13-23,00-05 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400 # Retener pod por 1 día
      template:
        spec:
          imagePullSecrets:
            - name: ghcr-secret
          containers:
            - name: send-dms
              image: ghcr.io/__GH_OWNER__/columnistosjs/send-dms:__VERSION__
              imagePullPolicy: IfNotPresent
              env:
                - name: WAFRN_EMAIL
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: WAFRN_EMAIL
                - name: WAFRN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: columnistos-secret
                      key: WAFRN_PASSWORD
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: DB_HOST
                - name: DB_USER
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: DB_USER
                - name: DB_PWD
                  valueFrom:
                    secretKeyRef:
                      name: columnistos-secret
                      key: DB_PWD
                - name: ADMIN_HANDLES
                  valueFrom:
                    configMapKeyRef:
                      name: columnistos-config
                      key: ADMIN_HANDLES
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
          restartPolicy: OnFailure
