name = "columnistos-predict-gender"
main = "index.js"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
